# For each integer n > 1 let, E(n) denote the sum of the integers from 1 to n.
# For example, E(100) = 1 + 2 + 3 ... + 100 = 5050. 
# What is the value of E(200)?

def E(n):
    # for i in range(1, n+1):
    # return sum(range(1, n+1))
    return n * (n + 1) // 2

result = E(200) 
print(result)

# The sequence of triangle numbers is generated by adding the natural numbers.
# So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
# The first ten terms would be:
# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

# Let us list the factors of the first seven triangle numbers:
#  1: 1
#  3: 1,3
#  6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28
# We can see that 28 is the first triangle number to have over five divisors.

# What is the value of the first triangle number to have over five hundred divisors?

def divisors(n):
    items = []
    for i in range(1, int(n**0.5) + 1):
        if n % i == 0:
            items.append(i)
            items.append(n//i)
    return items

for x in range(1, 1000000000000):
    if len(divisors(E(x))) > 500:
        print(x, E(x))
        break
